#ifndef BALANCESCREEN_GLOBAL_H
#define BALANCESCREEN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BALANCESCREEN_LIBRARY)
#define BALANCESCREEN_EXPORT Q_DECL_EXPORT
#else
#define BALANCESCREEN_EXPORT Q_DECL_IMPORT
#endif

#endif // BALANCESCREEN_GLOBAL_H
