#ifndef TRANSACTIONSWINDOW_GLOBAL_H
#define TRANSACTIONSWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QObject>
#include <QDialog>

#if defined(TRANSACTIONSWINDOW_LIBRARY)
#define TRANSACTIONSWINDOW_EXPORT Q_DECL_EXPORT
#else
#define TRANSACTIONSWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSACTIONSWINDOW_GLOBAL_H
