#ifndef TRANSFERRECEIVER_GLOBAL_H
#define TRANSFERRECEIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSFERRECEIVER_LIBRARY)
#define TRANSFERRECEIVER_EXPORT Q_DECL_EXPORT
#else
#define TRANSFERRECEIVER_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSFERRECEIVER_GLOBAL_H
