#ifndef CREDITPAYMENT_GLOBAL_H
#define CREDITPAYMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CREDITPAYMENT_LIBRARY)
#define CREDITPAYMENT_EXPORT Q_DECL_EXPORT
#else
#define CREDITPAYMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // CREDITPAYMENT_GLOBAL_H
