#ifndef CREDITWITHDRAW_GLOBAL_H
#define CREDITWITHDRAW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CREDITWITHDRAW_LIBRARY)
#define CREDITWITHDRAW_EXPORT Q_DECL_EXPORT
#else
#define CREDITWITHDRAW_EXPORT Q_DECL_IMPORT
#endif

#endif // CREDITWITHDRAW_GLOBAL_H
